apiVersion: v1
kind: ConfigMap
metadata:
  name: firefly-config
  namespace: firefly-platform
data:
  APP_ENV: "local"
  APP_DEBUG: "false"
  SITE_OWNER: "devops@example.com"
  APP_URL: "http://<FLOATING_IP>:30080"
  SESSION_DRIVER: "file"
  COOKIE_PATH: "/"
  COOKIE_SECURE: "false"
  COOKIE_SAMESITE: "lax"
  SPENDSENSE_SERVING_URL: "http://serving-baseline.firefly-platform.svc.cluster.local:8000"
  SPENDSENSE_SERVING_TIMEOUT: "3.0"
  DB_CONNECTION: "pgsql"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_DATABASE: "firefly"
  DB_USERNAME: "firefly"
  TRUSTED_PROXIES: "**"
