apiVersion: apps/v1
kind: Deployment
metadata:
  name: firefly
  namespace: firefly-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firefly
  template:
    metadata:
      labels:
        app: firefly
    spec:
      securityContext:
        fsGroup: 33
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: firefly
          image: spendsense/firefly-custom:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 33
            runAsGroup: 33
            runAsNonRoot: true
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: firefly-config
          env:
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: firefly-secret
                  key: APP_KEY
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
