apiVersion: apps/v1
kind: Deployment
metadata:
  name: firefly
  namespace: firefly-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firefly
  template:
    metadata:
      labels:
        app: firefly
    spec:
      containers:
        - name: firefly
          image: fireflyiii/core:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: firefly-config
          env:
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: firefly-secret
                  key: APP_KEY
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
