apiVersion: v1
kind: Service
metadata:
  name: serving-baseline
  namespace: firefly-platform
spec:
  type: NodePort
  selector:
    app: serving-baseline
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30081
